name: Auto update rust dependencies

# from: https://github.com/romoh/dependencies-autoupdate/blob/main/.github/workflows/autoupdate-dependencies-rust.yml

on:
  schedule:
    # runs daily at 12:00 am
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  auto-update-rust-dependencies:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false
          
    - name: Rust tools
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
             
    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@main
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'cargo update && cargo test'"
        
